name: 'Merge Branches'
description: 'Merge all PRs with the specified label into a branch.'
author: 'CodyTseng'
inputs:
  token:
    required: true
    description: 'GitHub token.'
  base:
    required: true
    description: 'The name of the base branch. Merge operations will be performed on the basis of this branch.'
  target:
    required: true
    description: 'The name of the target branch. This branch will be checked out from the base branch and accept all merges.'
  label-name:
    required: true
    description: 'The name of a label to find PRs to merge.'
  email:
    required: false
    default: merge-branches-bot@github.com
    description: 'The email of the committer.'
  name:
    required: false
    default: merge-branches-bot
    description: 'The name of the committer.'
runs:
  using: 'node16'
  main: 'dist/index.js'
