name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  token:
    required: true
  base:
    required: true
  target:
    required: true
  label-name:
    required: true
  email:
    required: false
    default: merge-prs-bot@github.com
  name:
    required: false
    default: merge-prs-bot
runs:
  using: 'node16'
  main: 'dist/index.js'
