name: 'Merge PRs by label'
description: 'Merge all PRs with the specified label into a branch based on the specified branch.'
author: 'CodyTseng'
inputs:
  token:
    required: true
  base:
    required: true
  target:
    required: true
  label-name:
    required: true
  email:
    required: false
    default: merge-prs-bot@github.com
  name:
    required: false
    default: merge-prs-bot
runs:
  using: 'node16'
  main: 'dist/index.js'
