name: 'test-action'
on:
  workflow_dispatch:
    inputs:
      base:
        description: 'The name of the base branch. Merge operations will be performed on the basis of this branch.'
        required: true
        default: 'main'
        type: string
      target:
        description: 'The name of the target branch. This branch will be checked out from the base branch and accept all merges.'
        required: true
        type: string
      label-name:
        description: 'The name of a label to find PRs to merge.'
        required: true
        type: string

permissions: write-all

jobs:
  merge-branches: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: codytseng/merge-branches-github-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ inputs.base }}
          target: ${{ inputs.target }}
          label-name: ${{ inputs.label-name }}
